In [1]:
%pylab inline
import pandas as pd
from IPython.html.widgets import interact

Populating the interactive namespace from numpy and matplotlib


:0: FutureWarning: IPython widgets are experimental and may change in the future.


In [2]:
#把index用columns[0]表示
df=pd.read_csv("history.csv",index_col=[0])

In [3]:
df[100:105]

TN  YN  year  month  day  x1  x2  x3  x4  x5  x6  s
100  101   3  2009      1    8   4   5  12  18  24  28  1
101  102   4  2009      1   12   9  13  14  23  29  36  8
102  103   5  2009      1   15   3  15  17  28  29  37  4
103  104   6  2009      1   19   1   3   4  12  21  31  8
104  105   7  2009      1   22   7  10  11  23  24  35  8

##target:對獎

In [4]:
a=0
def ini(a):
    """輸入購買的日期和號碼"""
    print ("第一區1~38選六,第二區（特別號）1~8選一")
    y=input('year ')
    m=input('month ')
    d=input('day ')
    x1=input('第一碼 ')
    x2=input('第二碼 ')
    x3=input('第三碼 ')
    x4=input('第四碼 ')
    x5=input('第五碼 ')
    x6=input('第六碼 ')
    s=input('特別號 ')
    #x=[int(y),int(m),int(d),int(x1)]
    x=array(list(map(int,[y,m,d,x1,x2,x3,x4,x5,x6,s])))
    return x

In [5]:
x=ini(a)

第一區1~38選六,第二區（特別號）1~8選一
year 2009
month 1
day 22
第一碼 1
第二碼 2
第三碼 34
第四碼 26
第五碼 6
第六碼 9
特別號 3


In [6]:
x

array([2009,    1,   22,    1,    2,   34,   26,    6,    9,    3])

In [3]:
#多重條件用(cond1)&(cond2)
def n(x):
    c=df[(df['year']==x[0]) & (df['month']==x[1]) & (df['day']==x[2])]#pandas裏的and
    #y=[int(c['x1']),int(c['x2']),int(c['x3']),int(c['x4']),int(c['x5']),int(c['x6']),int(c['s'])].values
    y=c[['x1','x2','x3','x4','x5','x6','s']].values[0]
    return y

In [4]:
lot = n(x)

NameError: name 'x' is not defined

In [9]:
lot

array([ 7, 10, 11, 23, 24, 35,  8])

array裡出現一項，把他取出來array[[1,2,3,4,5,6,7]]
d=d.values[0]

把他轉成純文字to_csv()
list(map(int, d.to_csv().split("\n")[1].split(",")[1:]))

eval("[" + d.to_csv().split("\n")[1] + "]")[1:]

eval("[a,'1',s,2]")

In [10]:
#x1是x取樂透號碼
x1=x[3:]
x1

array([ 1,  2, 34, 26,  6,  9,  3])

In [11]:
#對前六碼
def rec(lot,x1):
    a=0
    for i in lot[:6]:
        for j in x1[:6]:
            if i==j:a=a+1
    return a

In [12]:
f=rec(lot,x1)
f

0

In [13]:
#對最後一碼
m=int(x1[6]==lot[6])
m

0

In [14]:
u=[f,m]

In [15]:
def dis(u):
    '''印出中多少號碼和中獎金額跟項目'''
    dict={'[6, 1]':'頭獎',
          '[6, 0]':'貳獎',
          '[5, 1]':'參獎,新臺幣150,000元',
          '[5, 0]':'肆獎,新臺幣20,000元',
          '[4, 1]':'伍獎,新臺幣4,000元',
          '[4, 0]':'陸獎,新臺幣800元',
          '[3, 1]':'柒獎,新臺幣400元',
          '[3, 0]':'玖獎,新臺幣100元',
          '[2, 1]':'捌獎,新臺幣200元',
          '[2, 0]':'未中',
          '[1, 1]':'普獎,新臺幣100元',
          '[1, 0]':'未中',
          '[0, 1]':'未中',
          '[0, 0]':'未中'}
    if u[1]==0:
        print ("前六碼中"+str(f)+"碼，特別號沒中, 獎項是"+dict[str(u)]+".")
    else:
        print ("前六碼中"+str(f)+"碼，特別號有中！獎項是"+dict[str(u)]+".")
    
    
    

In [16]:
dis(u)

前六碼中0碼，特別號沒中, 獎項是未中.


In [17]:
%save receive_lotto_prize.py 1-16

File `receive_lotto_prize.py` exists. Overwrite (y/[N])?  y
The following commands were written to file `receive_lotto_prize.py`:
get_ipython().magic('pylab inline')
import pandas as pd
from IPython.html.widgets import interact
#把index用columns[0]表示
df=pd.read_csv("history.csv",index_col=[0])
df[100:105]
a=0
def ini(a):
    """輸入購買的日期和號碼"""
    print ("第一區1~38選六,第二區（特別號）1~8選一")
    y=input('year ')
    m=input('month ')
    d=input('day ')
    x1=input('第一碼 ')
    x2=input('第二碼 ')
    x3=input('第三碼 ')
    x4=input('第四碼 ')
    x5=input('第五碼 ')
    x6=input('第六碼 ')
    s=input('特別號 ')
    #x=[int(y),int(m),int(d),int(x1)]
    x=array(list(map(int,[y,m,d,x1,x2,x3,x4,x5,x6,s])))
    return x
x=ini(a)
x
#多重條件用(cond1)&(cond2)
def n(x):
    c=df[(df['year']==x[0]) & (df['month']==x[1]) & (df['day']==x[2])]#pandas裏的and
    #y=[int(c['x1']),int(c['x2']),int(c['x3']),int(c['x4']),int(c['x5']),int(c['x6']),int(c['s'])].values
    y=c[['x1','x2','x3','x4','x5','x6','s']].values[0]
    return y
lot 